services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=zdtl7y6p5r4q3w2e1a0s9d8f7g6h5j4k3l2m1n0b9v8c7x6z5l4k3j2h1mN2bV3
      - JWT_EXPIRATION=86400000
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG